apiVersion: apps/v1
kind: Deployment
# METADATA contacins labels
metadata:
  name: sretest-deployment
  labels: # labels
    app: sretest
# SPEC contains selectors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sretest
  # APPLIES TO A POD >>> blueprint
  template:
    metadata:
      labels: # labels
        app: sretest
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: "app"
      #               operator: In
      #               values:
      #                 - sretest
      containers:
        - name: sretest
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sretest-service
spec:
  selector:
    #Selectior for Deployment and Service should be the same.
    app: sretest #removed sretest-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # SHOULD MATCH  containerPort
